name: Push to main

on:
  push:
    branches:
      - main

jobs:
  linting:
    uses: ./.github/workflows/action_linting.yml

  test-build:
    uses: ./.github/workflows/action_test_build.yml

  sonarcloud:
    uses: ./.github/workflows/action_run_sonarcloud.yml
    secrets:
      github: ${{ secrets.GITHUB_TOKEN }}
      sonar: ${{ secrets.SONAR_TOKEN }}