name: Test unit

on: [ workflow_call ]


jobs:
  test:
    permissions:
      contents: write
      checks: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Add PNPM 8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install packages
        run: pnpm install

      - name: Format PNPM
        run: pnpm format

      - name: Run unit tests
        run: pnpm run test:unit

      - name: Run coverage
        run: pnpm run test:unit:coverage

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'test-report.xml'

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: junit-test-report
          path: ./test-report.xml
          retention-days: 14

      - name: Upload lcov test report
        uses: actions/upload-artifact@v2
        with:
          name: lcov-test-report
          path: |
            ./coverage/lcov.info
            ./coverage/lcov-report
          retention-days: 14